AWSTemplateFormatVersion: '2010-09-09'
Description: 'Medical OCR System - Complete Infrastructure with App Runner Container'

Parameters:
  GitHubRepository:
    Type: String
    Default: 'https://github.com/buckylee2019/medical-ocr-system'
    Description: 'GitHub repository URL'
  
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'GitHub branch to deploy'
  
  AppName:
    Type: String
    Default: 'medical-ocr-app'
    Description: 'Application name'

Resources:
  # S3 Bucket for image storage
  ImageStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-images-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, POST, PUT, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  # DynamoDB Table
  OCRDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AppName}-data'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: processing_mode
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: processing-mode-index
          KeySchema:
            - AttributeName: processing_mode
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # ECR Repository for container images
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}'
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # IAM Role for App Runner
  AppRunnerInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-instance-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Policies:
        - PolicyName: MedicalOCRAppPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: 
                  - !GetAtt OCRDataTable.Arn
                  - !Sub '${OCRDataTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ImageStorageBucket.Arn
                  - !Sub '${ImageStorageBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:ListFoundationModels
                Resource: '*'

  # IAM Role for App Runner Access (for ECR)
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-access-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppName
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:latest'
          ImageConfiguration:
            Port: '5006'
            RuntimeEnvironmentVariables:
              - Name: AWS_DEFAULT_REGION
                Value: !Ref AWS::Region
              - Name: DYNAMODB_TABLE_NAME
                Value: !Ref OCRDataTable
              - Name: S3_BUCKET
                Value: !Ref ImageStorageBucket
              - Name: FLASK_ENV
                Value: production
          ImageRepositoryType: ECR
          AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
        AutoDeploymentsEnabled: false
      InstanceConfiguration:
        Cpu: 1024
        Memory: 2048
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /health
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      AutoScalingConfigurationArn: !Ref AppRunnerAutoScalingConfig

  # Auto Scaling Configuration
  AppRunnerAutoScalingConfig:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub '${AppName}-autoscaling'
      MaxConcurrency: 100
      MaxSize: 25
      MinSize: 1

Outputs:
  AppRunnerServiceUrl:
    Description: 'App Runner Service URL'
    Value: !Sub 'https://${AppRunnerService.ServiceUrl}'
    Export:
      Name: !Sub '${AWS::StackName}-ServiceUrl'

  ECRRepositoryUri:
    Description: 'ECR Repository URI'
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}'
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepository'

  S3BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref ImageStorageBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  DynamoDBTableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref OCRDataTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTable'

  AppRunnerServiceArn:
    Description: 'App Runner Service ARN'
    Value: !GetAtt AppRunnerService.ServiceArn
    Export:
      Name: !Sub '${AWS::StackName}-ServiceArn'
